### ISSUE TITLE
Creating OSM Network Dataset in ArcGIS 10.3

### ISSUE THREAD

**Issue by ImranImmu** [Esri/arcgis-osm-editor#121]
Hi,
    I have tried creating OSM network dataset in ArcMap 10.3 using OSM Feature Dataset, But I'm getting this error:

Executing: OSMGPCreateNetworkDataset "S:\Network Analysis\Bangalore.gdb\Bangalore_OSM_Feature_Dataset" "C:\Program Files (x86)\ArcGIS\Desktop10.3\ArcToolbox\Toolboxes\ND_ConfigFiles\DriveMeters.xml" "S:\Network Analysis\Bangalore.gdb\Bangalore_OSM_Feature_Dataset\Bangalore_nd"
Start Time: Tue Apr 12 19:32:49 2016
The table was not found. [Bangalore_OSM_Feature_Dataset_osm_pt]
   at ESRI.ArcGIS.Geodatabase.IFeatureWorkspace.OpenFeatureClass(String Name)
   at ESRI.ArcGIS.OSM.GeoProcessing.NetworkDataset..ctor(String configXML, IDataset osmDataset, String ndsName, IGPMessages messages, ITrackCancel trackCancel)
   at ESRI.ArcGIS.OSM.GeoProcessing.OSMGPCreateNetworkDataset.Execute(IArray paramvalues, ITrackCancel TrackCancel, IGPEnvironmentManager envMgr, IGPMessages message)
Failed to execute (OSMGPCreateNetworkDataset).
Failed at Tue Apr 12 19:32:54 2016 (Elapsed Time: 5.33 seconds)

I've Tried to create ND using both Enable/Disable Background Processing and I have installed ArcGISEditor OSMToolbox 64 Bit.

Can anyone guide me through this?

**Comment by mboeringa** [comment]
I can't help you with the specifics, as I have not yet used the Network Dataset options, but looking at the error message, it says that the **Bangalore_OSM_Feature_Dataset_osm_pt** table / dataset was not found. This should be, based on the **_pt** suffix, a Point feature class in your geodatabase in the selected feature dataset. Can you confirm you have such a point feature class in your OSM geodatabase?

**Comment by ImranImmu** [comment]
mboeringa, I would like to thank you for your suggestion.

I have figured out the problem. Actually after creating the Feature Dataset i've renamed the features because of which it was showing the error. I again tried the same without modifying the features and i got the result.

**Comment by doccer** [comment]
Hi ImranImmu

I am having the exact same issue.  Can you describe your solution more?  What did you rename the feature dataset from and to for example?

Thanks.

Executing: OSMGPCreateNetworkDataset The table was not found. [Dublin_OSM1_osm_pt]

**Comment by ImranImmu** [comment]
@doccer, Have you renamed any of the feature classes within the Feature Dataset before creating a Network Dataset?

**Comment by ImranImmu** [comment]
@doccer, go through the attachment once.
[Creating OSM Network Dataset using OSM Toolbox.docx](https://github.com/Esri/arcgis-osm-editor/files/1105084/Creating.OSM.Network.Dataset.using.OSM.Toolbox.docx)
