### ISSUE TITLE
Creating OSM Network Dataset using Confg Files in ArcGIS 10.3

### ISSUE THREAD

**Issue by ImranImmu** [Esri/arcgis-osm-editor#122]
Hi,
    I have been trying to create a OSM Network dataset by giving "DriveGeneric.xml" as config File. But, I'm getting the error which follows:

Executing: OSMGPCreateNetworkDataset "D:\Remaining\N Analysis\OSM_FD_ND.gdb\Bangalore_Feature_Dataset" "C:\Program Files (x86)\ArcGIS\Desktop10.3\ArcToolbox\Toolboxes\ND_ConfigFiles\DriveMeters.xml" "D:\Remaining\N Analysis\OSM_FD_ND.gdb\Bangalore_Feature_Dataset\Bangalore_Feature_Dataset_nd_DriveMeters"
Start Time: Wed Apr 13 12:29:21 2016
Extracting Edge Features
OSMGPAttributeSelector_osmtools
Executing: OSMGPAttributeSelector "D:\Remaining\N Analysis\OSM_FD_ND.gdb\Bangalore_Feature_Dataset\Bangalore_Feature_Dataset_osm_ln" construct;proposed;maxheight;maxspeed
Start Time: Wed Apr 13 12:29:21 2016
Adding field osm_construct based on tag key construct.
Adding field osm_proposed based on tag key proposed.
Adding field osm_maxheight based on tag key maxheight.
Adding field osm_maxspeed based on tag key maxspeed.
useUpdateCursor: True
Succeeded at Wed Apr 13 12:30:02 2016 (Elapsed Time: 40.83 seconds)
Select_analysis
Executing: Select "D:\Remaining\N Analysis\OSM_FD_ND.gdb\Bangalore_Feature_Dataset\Bangalore_Feature_Dataset_osm_ln" "D:\Remaining\N Analysis\OSM_FD_ND.gdb\Bangalore_Feature_Dataset\Bangalore_Feature_Dataset_nd_DriveMeters_roads" "(highway IS NOT NULL) AND (LOWER(highway) in ('motorway','motorway_link','trunk','trunk_link','primary','primary_link','secondary','secondary_link','tertiary','tertiary_link','living_street','residential','unclassified','road'))"
Start Time: Wed Apr 13 12:30:02 2016
Succeeded at Wed Apr 13 12:30:15 2016 (Elapsed Time: 12.88 seconds)
Extracting Junction Features
Select_analysis
Executing: Select "D:\Remaining\N Analysis\OSM_FD_ND.gdb\Bangalore_Feature_Dataset\Bangalore_Feature_Dataset_osm_pt" "D:\Remaining\N Analysis\OSM_FD_ND.gdb\Bangalore_Feature_Dataset\Bangalore_Feature_Dataset_nd_DriveMeters_barriers" "(barrier IS NOT NULL) AND (LOWER(barrier) in ('block','bollard','chain','debris','jersey_barrier','lift_gate','log','spikes','swing_gate'))"
Start Time: Wed Apr 13 12:30:15 2016
Succeeded at Wed Apr 13 12:31:19 2016 (Elapsed Time: 1 minutes 3 seconds)
Assigning Network Connectivity Groups
Extracting Turn Restrictions
CreateTurnFeatureClass_na
Executing: CreateTurnFeatureClass "D:\Remaining\N Analysis\OSM_FD_ND.gdb\Bangalore_Feature_Dataset" Bangalore_Feature_Dataset_nd_DriveMeters_turns 2 # # # # 0 0 0 DISABLED
Start Time: Wed Apr 13 12:32:06 2016
Succeeded at Wed Apr 13 12:32:07 2016 (Elapsed Time: 0.64 seconds)
AddField_management
Executing: AddField "D:\Remaining\N Analysis\OSM_FD_ND.gdb\Bangalore_Feature_Dataset\Bangalore_Feature_Dataset_nd_DriveMeters_turns" RestrictionType TEXT # # 30 # NULLABLE NON_REQUIRED #
Start Time: Wed Apr 13 12:32:07 2016
Adding RestrictionType to D:\Remaining\N Analysis\OSM_FD_ND.gdb\Bangalore_Feature_Dataset\Bangalore_Feature_Dataset_nd_DriveMeters_turns...
Succeeded at Wed Apr 13 12:32:07 2016 (Elapsed Time: 0.15 seconds)
Populating Turn Features from OSM Relations
Adding Network Attributes
Creating Network Dataset
Exception from HRESULT: 0x80042288
   at ESRI.ArcGIS.Geodatabase.IDatasetContainer2.CreateDataset(IDEDataset DataElement)
   at ESRI.ArcGIS.OSM.GeoProcessing.NetworkDataset.CreateBuildableNDS()
   at ESRI.ArcGIS.OSM.GeoProcessing.RunTaskManager.ExecuteTask(String messageName, Action task)
   at ESRI.ArcGIS.OSM.GeoProcessing.NetworkDataset.CreateNetworkDataset()
   at ESRI.ArcGIS.OSM.GeoProcessing.OSMGPCreateNetworkDataset.Execute(IArray paramvalues, ITrackCancel TrackCancel, IGPEnvironmentManager envMgr, IGPMessages message)
Failed to execute (OSMGPCreateNetworkDataset).
Failed at Wed Apr 13 12:33:13 2016 (Elapsed Time: 3 minutes 52 seconds)

And i would like to remind you that while using "CycleGeneric.Xml" as config file i'm able to Create OSM Network Dataset. The above error is coming whenever i am giving "DriveGeneric.xml" or "Drivemetre.xml:" as Config file.

**Comment by semm1968** [comment]
I think the problem that the Drivemetre.xml expect the fields
- maxheight
- proposed
- construction
- highway

So you have to add the field in the load process and propagate the field with values in the OSMGPAttributeSelector_osmtools tool.

I also adjusted the field names in the drivemetre.xml from 'contruct' to 'construction'. So it matches the OSM nomination.

Attached a python script and the adjusted drivemetre_2.xml
[na_osm.zip](https://github.com/Esri/arcgis-osm-editor/files/3563510/na_osm.zip)
 which automates the process (directories have to be adjusted). 
One thing is still missing in my opinion in the script is that you have to change the coordinate system from WGS84 to a projected coordinate system.

**Comment by ThomasEmge** [comment]
@semm1968 I hear you with respect to the projected coordinate system. We would probably need to adjust the documentation to remind users to consider the data usage before loading the data and adjust the target spatial reference accordingly.

**Comment by RustanElan** [comment]
It is unbelievable how much a waste of time this lead me to....I was running a full country network dataset creation and after waiting for 13 DAYS (!) it gave me the error above...I wasted 2 weeks because someone messed up with the code. Being recommended by ESRI this tool should be WAY better and fully debugged already...
I'm just so frustrated
