### ISSUE TITLE
Create Network Dataset 10.4

### ISSUE THREAD

**Issue by aots74** [Esri/arcgis-osm-editor#129]
I am attempting to create a network dataset after using the "OSM File Loader (Load only)" tool. Everything runs successfully until the error below. I note that it relates to OSM relations and unlike the original method of loading OSM, the (load only) tool doesn't create a relations table. I'm not sure, however, if that is the problem. Also note the tools node, relation and way loader but not sure if I need to, or how to, run them. As always, any advice greatly appreciated!

Populating Turn Features from OSM Relations

The operation was attempted on an empty geometry.
   at ESRI.ArcGIS.Geodatabase.IFeatureWorkspace.OpenTable(String Name)
   at ESRI.ArcGIS.OSM.GeoProcessing.NetworkTurns.<EnumerateOsmTurnRestrictions>d__2.MoveNext()
   at ESRI.ArcGIS.OSM.GeoProcessing.NetworkTurns.PopulateTurnsFromRelations()
   at ESRI.ArcGIS.OSM.GeoProcessing.RunTaskManager.ExecuteTask(String messageName, Action task)
   at ESRI.ArcGIS.OSM.GeoProcessing.NetworkTurns.ExtractTurnRestrictions()
   at ESRI.ArcGIS.OSM.GeoProcessing.NetworkDataset.ExtractTurnRestrictions()
   at ESRI.ArcGIS.OSM.GeoProcessing.RunTaskManager.ExecuteTask(String messageName, Action task)
   at ESRI.ArcGIS.OSM.GeoProcessing.NetworkDataset.CreateNetworkDataset()
   at ESRI.ArcGIS.OSM.GeoProcessing.OSMGPCreateNetworkDataset.Execute(IArray paramvalues, ITrackCancel TrackCancel, IGPEnvironmentManager envMgr, IGPMessages message)
Failed to execute (OSMGPCreateNetworkDataset).
Failed at Thu May 26 10:36:44 2016 (Elapsed Time: 2 hours 58 minutes 34 seconds)

**Comment by ThomasEmge** [comment]
My apologies for leading you down the wrong path with the load only tool. Turn restrictions are not processed as part of this tool (or the relation loader tool respectively) and hence these feature classes cannot be used to build a network. Unfortunately you have to use the full featured (and slower) loading tool to gather this information.
Technically speaking the tool should not fail and just continue without the turn restriction information.

**Comment by mboeringa** [comment]
> Technically speaking the tool should not fail and just continue without the turn restriction information.

From a user perspective, I think it more desirable if the tool blocked usage of datasets created using the 'load only' tool, instead of continuing without turn restrictions, and displayed a warning message about the reason. It will be even more confusing if the tool apparently succeeds, only to discover later on that the resulting Network Dataset doesn't have turn restrictions.

It shouldn't be to difficult to write some validation code that can detect the current status of the layers ('load only' or normal). You probably already have that in the code anyway.

**Comment by aots74** [comment]
No worries Thomas. In the end perhaps the problems identified with the load only tool might apply to the full load though I'm not sure. I tried running a 32-bit instance of the full load tool and I did not encounter the error that led me to the previous issue. 49 hours later - successful load. I've just kicked off the network dataset tool and I'm guessing it will also succeed. So possibly down to some problems with 64-bit processing?
