### ISSUE TITLE
Create OSM Network Dataset crashes at creating network dataset

### ISSUE THREAD

**Issue by elaraa** [Esri/arcgis-osm-editor#168]
I downloaded a set of OSM data and trying to create a network dataset with the data. The tool Create OSM Network Dataset crashed all the time when it reach the create network dataset according the the log message. 
These files have been before the crash: StudyArea_nd_barriers, StudyArea_nd_roads, StudyArea_nd_turns. Can manually create a network dataset with these data?

**Comment by ThomasEmge** [comment]
We had another user with a (maybe) similar issue. Depending on the size of your study please ensure that you have sufficient disk space in the OS defined temp folder location.
What do you mean by "crashed"? The whole application crashes or the execution of the tool returns with an error? If it is the error case and you still have the log messages, please post the messages in the thread. It helps us narrow down the underlying issues.
And yes, you certainly can build the network yourself using the extracted _roads, _turns, and _barriers feature classes as inputs.

**Comment by elaraa** [comment]
ArcMap crashed without returning any error message. Ok, I will try to create the network dataset. Thank you.

**Comment by elizasth** [comment]
Hello I am also facing the same problem. I am trying to create a model which has the following process:
Load OSM file followed by create network dataset.

While i run the model for the first time, It works fine. but when i try to re-run the model. It gives me error as below:
Exception from HRESULT: 0x80042267
   at ESRI.ArcGIS.Geodatabase.IDatasetContainer2.CreateDataset(IDEDataset DataElement)
   at ESRI.ArcGIS.OSM.GeoProcessing.NetworkDataset.CreateBuildableNDS()
   at ESRI.ArcGIS.OSM.GeoProcessing.RunTaskManager.ExecuteTask(String messageName, Action task)
   at ESRI.ArcGIS.OSM.GeoProcessing.NetworkDataset.CreateNetworkDataset()
   at ESRI.ArcGIS.OSM.GeoProcessing.OSMGPCreateNetworkDataset.Execute(IArray paramvalues, ITrackCancel TrackCancel, IGPEnvironmentManager envMgr, IGPMessages message)
Failed to execute (Create OSM Network Dataset).

I tried both by enabling and disabling the geoprocessing option.
but it doesnot works.
If you have any solutions. then please let me know.

**Comment by elizasth** [comment]
I canged the Xml file and now i am getting lock error..

**Comment by jan1909** [comment]
> Hello I am also facing the same problem. I am trying to create a model which has the following process:
> Load OSM file followed by create network dataset.
> 
> While i run the model for the first time, It works fine. but when i try to re-run the model. It gives me error as below:
> Exception from HRESULT: 0x80042267
> at ESRI.ArcGIS.Geodatabase.IDatasetContainer2.CreateDataset(IDEDataset DataElement)
> at ESRI.ArcGIS.OSM.GeoProcessing.NetworkDataset.CreateBuildableNDS()
> at ESRI.ArcGIS.OSM.GeoProcessing.RunTaskManager.ExecuteTask(String messageName, Action task)
> at ESRI.ArcGIS.OSM.GeoProcessing.NetworkDataset.CreateNetworkDataset()
> at ESRI.ArcGIS.OSM.GeoProcessing.OSMGPCreateNetworkDataset.Execute(IArray paramvalues, ITrackCancel TrackCancel, IGPEnvironmentManager envMgr, IGPMessages message)
> Failed to execute (Create OSM Network Dataset).
> 
> I tried both by enabling and disabling the geoprocessing option.
> but it doesnot works.
> If you have any solutions. then please let me know.

I have the exact same problem. Did you find any solution yet?

**Comment by elizasth** [comment]
> > Hello I am also facing the same problem. I am trying to create a model which has the following process:
> > Load OSM file followed by create network dataset.
> > While i run the model for the first time, It works fine. but when i try to re-run the model. It gives me error as below:
> > Exception from HRESULT: 0x80042267
> > at ESRI.ArcGIS.Geodatabase.IDatasetContainer2.CreateDataset(IDEDataset DataElement)
> > at ESRI.ArcGIS.OSM.GeoProcessing.NetworkDataset.CreateBuildableNDS()
> > at ESRI.ArcGIS.OSM.GeoProcessing.RunTaskManager.ExecuteTask(String messageName, Action task)
> > at ESRI.ArcGIS.OSM.GeoProcessing.NetworkDataset.CreateNetworkDataset()
> > at ESRI.ArcGIS.OSM.GeoProcessing.OSMGPCreateNetworkDataset.Execute(IArray paramvalues, ITrackCancel TrackCancel, IGPEnvironmentManager envMgr, IGPMessages message)
> > Failed to execute (Create OSM Network Dataset).
> > I tried both by enabling and disabling the geoprocessing option.
> > but it doesnot works.
> > If you have any solutions. then please let me know.
> 
> I have the exact same problem. Did you find any solution yet?

No, I haven't solved yet. I get the same error

**Comment by jan1909** [comment]
> > > Hello I am also facing the same problem. I am trying to create a model which has the following process:
> > > Load OSM file followed by create network dataset.
> > > While i run the model for the first time, It works fine. but when i try to re-run the model. It gives me error as below:
> > > Exception from HRESULT: 0x80042267
> > > at ESRI.ArcGIS.Geodatabase.IDatasetContainer2.CreateDataset(IDEDataset DataElement)
> > > at ESRI.ArcGIS.OSM.GeoProcessing.NetworkDataset.CreateBuildableNDS()
> > > at ESRI.ArcGIS.OSM.GeoProcessing.RunTaskManager.ExecuteTask(String messageName, Action task)
> > > at ESRI.ArcGIS.OSM.GeoProcessing.NetworkDataset.CreateNetworkDataset()
> > > at ESRI.ArcGIS.OSM.GeoProcessing.OSMGPCreateNetworkDataset.Execute(IArray paramvalues, ITrackCancel TrackCancel, IGPEnvironmentManager envMgr, IGPMessages message)
> > > Failed to execute (Create OSM Network Dataset).
> > > I tried both by enabling and disabling the geoprocessing option.
> > > but it doesnot works.
> > > If you have any solutions. then please let me know.
> > 
> > 
> > I have the exact same problem. Did you find any solution yet?
> 
> No, I haven't solved yet. I get the same error

Ive noticed that i get this error only while using the DriveMeters.xml as network config file. With DriveGeneric.xml its all good. Ive read somewhere else that changing the unit in ArcMap and in the config file to km could help, but i cant verify that yet. But i would assume the problem is within the DriveMeters.xml, atleast for me. Which config file do you use?

**Comment by ShangbinTANG** [comment]
> 

Hi guys I have the same issue and changing to DriveGeneric.xml didn't help in the beginning, but it works after i turned off the background processing. hope this might help :)

**Comment by ShangbinTANG** [comment]
Hi guys I have the same issue and changing to DriveGeneric.xml didn't help in the beginning, but it works after i turned off the background processing. hope this might help :)
