### ISSUE TITLE
TypeError: OSMGPFileLoader() takes 0 positional arguments but 7 were given

### ISSUE THREAD

**Issue by neogeomat** [Esri/arcgis-osm-editor#197]
I exported a working model to python and i am trying to run it from arcpy. I have imported the toolbox. 

This line 
 `arcpy.OSMGPFileLoader_osmtools(interpreter_osm, "CONSERVE_MEMORY", "", overpass, overpass_osm_pt, overpass_osm_ln, overpass_osm_ply)`
gives
`Traceback (most recent call last):
  File "D:\neogeomat\Documents\ArcGIS\Projects\Eliza\elizapasaexport.py", line 33, in <module>
    arcpy.OSMGPFileLoader_osmtools(interpreter_osm, "CONSERVE_MEMORY", "", overpass, overpass_osm_pt, overpass_osm_ln, overpass_osm_ply)
TypeError: OSMGPFileLoader() takes 0 positional arguments but 7 were given`

Removing arguments
`arcpy.OSMGPFileLoader_osmtools()`
gives 
`Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    arcpy.OSMGPFileLoader_osmtools()
  File "c:\Program Files (x86)\arcgis\desktop10.6\ArcToolbox\Toolboxes\OpenStreetMap Toolbox.tbx", line 173, in OSMGPFileLoader
    `

**Comment by ThomasEmge** [comment]
I think the error message might be misleading at this point. The max is 6 arguments and you are providing 7.


This is from the tool help:

```
# load the stand-alone OSM file and store it in the target feature dataset
arcpy.OSMGPFileLoader_osmtools(r'c:\temp\map.osm', 'CONSERVE_MEMORY', nameOfTargetDataset, nameOfPointFeatureClass, nameOfLineFeatureClass, nameOfPolygonFeatureClass)
```

**Comment by xeir83** [comment]
I just faced the same issue when trying my script on a lower version (at my server) of the OSM toolbox. My script works just fine on the toolbox for 10.6, but when executed for the toolbox in 10.2 i got the same error as you. Will try upgrading the toolbox to 10.3 in the next week to see if the problem persists.
