### ISSUE TITLE
OSMGPCreateNetworkDataset: The target dataset [..] is locked.

### ISSUE THREAD

**Issue by Chaz6** [Esri/arcgis-osm-editor#207]
When trying to generate a network dataset, it fails every time with the message `The target dataset: '[..]' is locked.`

Full output:-

```
Messages
Executing: OSMGPCreateNetworkDataset D:\Downloads\openstreetmap.gdb\leics "D:\Program Files\ArcGIS\Desktop10.7\ArcToolbox\Toolboxes\ND_ConfigFiles\DriveGeneric.xml" D:\Downloads\openstreetmap.gdb\leics\leics_nd
Start Time: Fri Jun 14 15:18:05 2019

Extracting Edge Features

Select_analysis


The target dataset: 'D:\Downloads\openstreetmap.gdb\leics\leics_nd_roads' is locked.
   at ESRI.ArcGIS.OSM.GeoProcessing.NetworkDataset.SelectFeaturesToNewFeatureClass(String source, String target, String query)
   at ESRI.ArcGIS.OSM.GeoProcessing.NetworkDataset.ExtractEdgeFeatureClasses()
   at ESRI.ArcGIS.OSM.GeoProcessing.RunTaskManager.ExecuteTask(String messageName, Action task)
   at ESRI.ArcGIS.OSM.GeoProcessing.NetworkDataset.CreateNetworkDataset()
   at ESRI.ArcGIS.OSM.GeoProcessing.OSMGPCreateNetworkDataset.Execute(IArray paramvalues, ITrackCancel TrackCancel, IGPEnvironmentManager envMgr, IGPMessages message)
Failed to execute (OSMGPCreateNetworkDataset).
Failed at Fri Jun 14 15:18:06 2019 (Elapsed Time: 1.11 seconds)
```

**Comment by Chaz6** [comment]
I was able to capture additional output by running in the foreground:-

```
[..]
Start Time: Fri Jun 14 15:29:20 2019
Extracting Edge Features
Select_analysis
Executing: Select D:\Downloads\openstreetmap.gdb\leics\leics_osm_ln D:\Downloads\openstreetmap.gdb\leics\leics_nd_roads "(highway IS NOT NULL) AND (LOWER(highway) in ('motorway','motorway_link','trunk','trunk_link','primary','primary_link','secondary','secondary_link','tertiary','tertiary_link','living_street','residential','unclassified','road'))"
Start Time: Fri Jun 14 15:29:20 2019
ERROR 000358: Invalid expression (highway IS NOT NULL) AND (LOWER(highway) in ('motorway','motorway_link','trunk','trunk_link','primary','primary_link','secondary','secondary_link','tertiary','tertiary_link','living_street','residential','unclassified','road'))
Failed to execute (Select).
Failed at Fri Jun 14 15:29:21 2019 (Elapsed Time: 0.47 seconds)
[..]
```

I think this is because the tool `OSM File Loader (Load only)` appends the prefix `osm_` to the field names. Normally I would use the tool `Load OSM File` but it failed on the target *.osm file (error about missing dictionay key IIRC). I would suggest either change the tool `OSM File Loader (Load only)` to remove the `osm_` prefix, or change `Create OSM Network Dataset` so that it checks for the prefixed field names.
