### ISSUE TITLE
Create OSM Network Dataset

### ISSUE THREAD

**Issue by AndersVittrup** [Esri/arcgis-osm-editor#93]
Hi,

I have tried createing OSM network dataset in both ArcMap 10.1 and 10.3 and they fail.
I'm getting this error:

--- snap ---
Assigning Network Connectivity Groups
Extracting Turn Restrictions
Exception from HRESULT: 0x80040353
   at ESRI.ArcGIS.Geodatabase.IDatasetContainer2.CreateDataset(IDEDataset DataElement)
   at ESRI.ArcGIS.OSM.GeoProcessing.NetworkDataset.CreateTempNDS()
   at ESRI.ArcGIS.OSM.GeoProcessing.NetworkDataset.ExtractTurnRestrictions()
   at ESRI.ArcGIS.OSM.GeoProcessing.RunTaskManager.ExecuteTask(String messageName, Action task)
   at ESRI.ArcGIS.OSM.GeoProcessing.NetworkDataset.CreateNetworkDataset()
   at ESRI.ArcGIS.OSM.GeoProcessing.OSMGPCreateNetworkDataset.Execute(IArray paramvalues, ITrackCancel TrackCancel, IGPEnvironmentManager envMgr, IGPMessages message)
Failed to execute (OSMGPCreateNetworkDataset).
Failed at Mon Aug 24 12:58:49 2015 (Elapsed Time: 11 minutes 14 seconds)

How to solve this?

**Comment by eggwhites** [comment]
Hello - one question: do you have the "Enable" box checked for Background Geoprocessing in the Geoprocessing options? It will be required for the tool to execute.

More on enabling/disabling background geoprocessing options here (doc for 10.2 works the same in other versions): http://resources.arcgis.com/en/help/main/10.2/index.html#//00210000003q000000

**Comment by AndersVittrup** [comment]
I have disabled the background processing. Else i can't run load osm from file.
I have tested on another machine 32 bit and it all worked. The machine having issues is running 64 bit but i think arcgis is 32 bit on the machine. Maybe This is causing problems?

**Comment by mboeringa** [comment]
> The machine having issues is running 64 bit but i think arcgis is 32 bit on the machine. Maybe This is causing problems?

That shouldn't cause problems, 32 bit software can run without issues on 64 bit windows, and that includes ArcGIS. 32 bit software just can't take advantage of 64 bit address space and large RAM effectively.

Also see here:

http://windows.microsoft.com/en-us/windows/32-bit-and-64-bit-windows#1TC=windows-7

If the Create OSM Network Dataset tool requires large amounts of RAM to do its job properly, then that might be part of the answer to the question why its better to run it as 64 bit background geoprocessing process.

**Comment by ThomasEmge** [comment]
I am guessing that the 64bit geoprocessing option is installed on your machine. With this option installed and the GP environment set to Background you need to install the 64bit version of the OSM tools. 
That is the second installer under 'ArcGISEditor10_3_x64'. This set of tools which contains the same functionality as the first installer is specifically needed to run in the 64bit context of desktop background and ArcGIS Server.

On more general terms, all 32bit software runs just fine on 64bit operating systems. This will not be an issue. However please do run the Create Network in the foreground if you are using a file geodatabase. We are aware of a locking issue if certain tools are running in succession. Creating large networks (even on 32bit) will not be an issue either, it might just mean that the tool's internal dynamic resource allocation kicks in a little sooner but all that are implementation details. Bottom line, running 32bit application on 64bit OSes just works.

**Comment by EtachGu** [comment]
I also get this problem...  
Dose the configuration file cause it ?

**Comment by ThomasEmge** [comment]
Please run this tool as a foreground geoprocessing tool. Here is some documentation on the difference and how to switch http://desktop.arcgis.com/en/arcmap/latest/analyze/executing-tools/foreground-and-background-processing.htm

**Comment by DiegoSalcedo** [comment]
I am also getting this error, it is running in the foreground and I get the same exact failure initially reported.
Running 10.2.1.

**Comment by ThomasEmge** [comment]
Unfortunately the error message isn't revealing any reason for the error. By sure to follow the steps outlined in the wiki https://github.com/Esri/arcgis-osm-editor/wiki/Create-a-network-dataset-from-osm-data

**Comment by kevinpdavies** [comment]
I also had this problem. I was running with a new blank map. I changed the coordinate system to WGS84 and tried again and it worked for me.

**Comment by Chaz6** [comment]
After much trial and error with various things, I was able to make this work by first creating a simple network dataset, I then created a new configuration *.xml using the XMLFromNDS.py script, then using this in the **Create OSM Network Dataset** tool. I hope this helps someone!

**Comment by GravitaZ** [comment]
@Chaz6 is it possible I can get a copy of your config file? this error is driving me insane, or are they very easy to do yourself?

**Comment by GravitaZ** [comment]
> I am also getting this error, it is running in the foreground and I get the same exact failure initially reported.
> Running 10.2.1.
> 
> This is my error:
> 
> Start Time: Thu Feb 23 15:04:43 2017
> Succeeded at Thu Feb 23 15:04:48 2017 (Elapsed Time: 5.00 seconds)
> Assigning Network Connectivity Groups
> Extracting Turn Restrictions
> Exception from HRESULT: 0x80040353
> at ESRI.ArcGIS.Geodatabase.IDatasetContainer2.CreateDataset(IDEDataset DataElement)
> at ESRI.ArcGIS.OSM.GeoProcessing.NetworkDataset.CreateTempNDS()
> at ESRI.ArcGIS.OSM.GeoProcessing.NetworkDataset.ExtractTurnRestrictions()
> at ESRI.ArcGIS.OSM.GeoProcessing.RunTaskManager.ExecuteTask(String messageName, Action task)
> at ESRI.ArcGIS.OSM.GeoProcessing.NetworkDataset.CreateNetworkDataset()
> at ESRI.ArcGIS.OSM.GeoProcessing.OSMGPCreateNetworkDataset.Execute(IArray paramvalues, ITrackCancel TrackCancel, IGPEnvironmentManager envMgr, IGPMessages message)
> Failed to execute (OSMGPCreateNetworkDataset).
> Failed at Thu Feb 23 15:04:49 2017 (Elapsed Time: 9.45 seconds)
> 
> Any help solving this would be appreciated.

@DiegoSalcedo did you ever solve this problem?
